# -*- coding: utf-8 -*-
"""EM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NQhnUXOqkSrt6tW_7ILp51B4O0vwsSGw
"""

# Commented out IPython magic to ensure Python compatibility.
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()


import warnings ; warnings.filterwarnings('ignore')
import seaborn as sns
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, StratifiedKFold 
skf = StratifiedKFold(n_splits=10) 
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import sys

from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_samples, silhouette_score
# %matplotlib inline 

# Import the data file
#df = pd.read_csv('E:\PythonWorkSpace\s2\lab2\housing.csv', encoding='utf-8')
df = pd.read_csv('/content/drive/MyDrive/머신러닝/housing.csv')
print(df.dtypes)
print(df.isna().sum())

##setting data set
#ex = df.iloc[:,8]
df = df.drop('median_house_value',axis=1)
#df['median_house_value'] = ex.to_numpy()


#fill na in total_bedrooms
#I thought it was marked Na because the value is 0.
df = df.fillna(0)
print(df.isna().sum())

X1 = df[['total_rooms','total_bedrooms','population']]

scaler = preprocessing.StandardScaler()
scaler.fit(X1)
scale_X1=scaler.transform(X1)

k_num ={2,3,4,5,7,10}
for k in k_num:
  c_mdel = GaussianMixture(n_components=k, random_state=0).fit(scale_X1)
  c_mdel_cluster_labels = c_mdel.predict(scale_X1)

  X1['cluster'] = c_mdel_cluster_labels
  print( X1['cluster'])
  sample_score = silhouette_samples(X1,X1['cluster'])
  X1['silhouette_'] = sample_score
  print('aver sihouette_: ' +str(X1['silhouette_'].mean()))
  X1.groupby('cluster')['silhouette_'].mean()